/** Declaration file generated by dts-gen */

export = traceback;

declare function traceback(): any;

declare namespace traceback {
    const prototype: {
    };

    function raw(): any;

    namespace raw {
        const prototype: {
        };

    }

    namespace v8 {
        function FormatStackTrace(error: any, frames: any): any;

        namespace FormatStackTrace {
            const prototype: {
            };

        }

    }

}

